DROP TABLE IF EXISTS linkPermission;
DROP TABLE IF EXISTS categoryPermission;
DROP TABLE IF EXISTS gdlinks;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS sessionSemester;
